services:

  mongo:
    image: mongo
    env_file: '.env'
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - './.database/mongo:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
