service: nest-sls-template

frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  timeout: 20

functions:
  main:
    handler: dist/main.handlers.http
    events:
      - httpApi: '*'

  WSConnect:
    handler: dist/main.handlers.ws.connection
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect

  WSDefault:
    handler: dist/main.handlers.ws.default
    events:
      - websocket:
          route: $default




